databases:
  - name: Jungle
    databaseName: jungle_db
    user: jungle_user

services:
  - type: web
    name: Jungle
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: Jungle
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false